version: "3"

services:
  authentication:
    build: ./auth
    command: python auth.py

  enterData:
    build: ./enter-data
    command: python enter-data.py
    
  vote:
    build: ./vote
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"

  mongoDB:
    image: mongo:latest
    ports: ["6379"]

  db:
    image: mysql:5.7
    ports:
       - "33061:3306"
    command: --init-file /mysql/init.sql
    volumes:
       - db_data:/var/lib/mysql
       - ./init.sql:/mysql/init.sql
    environment:
       MYSQL_ROOT_USER: root
       MYSQL_ROOT_PASSWORD: 12345
       MYSQL_USER: docker
       MYSQL_PASSWORD: docker
       MYSQL_DB: docker
    restart: always

#   result:
#     build: ./result
#     command: nodemon server.js
#     volumes:
#       - ./result:/app
#     ports:
#       - "5001:80"
#       - "5858:5858"

volumes:
  db-data:

networks:
  front-tier:
  back-tier:

