---
version: "3"

services:
  authentication:
    build: ./auth
    command: python auth.py
    
  vote:
    build: ./vote
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"

  mongoDB:
    image: mongo:latest
    ports: ["6379"]

  worker:
    build: ./worker

  db:
    build: ./mysql
      dockerfile: /Dockerfile
    volumes:
       - db_data:/var/lib/mysql
    restart: always

  result:
    build: ./result
    command: nodemon server.js
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
